POST http://localhost:3001/api/notes
content-type: application/json

{
  "content": "This is a new note by Julkli129 but is not important",
  "important": false,
  "userId": "6065eace8b8233117cea7356"
}